export const moviesNull = '';

export const movies = [
  {
    adult: false,
    backdrop_path: '/2I5eBh98Q4aPq8WdQrHdTC8ARhY.jpg',
    genre_ids: [28, 12, 16, 878],
    id: 569094,
    original_language: 'en',
    original_title: 'Spider-Man: Across the Spider-Verse',
    overview:
      'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.',
    popularity: 2824.652,
    poster_path: '/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    release_date: '2023-05-31',
    title: 'Spider-Man: Across the Spider-Verse',
    video: false,
    vote_average: 8.8,
    vote_count: 852,
  },
  {
    adult: false,
    backdrop_path: '/94TIUEhuwv8PhdIADEvSuwPljS5.jpg',
    genre_ids: [28, 10752],
    id: 840326,
    original_language: 'fi',
    original_title: 'Sisu',
    overview:
      'Deep in the wilderness of Lapland, Aatami Korpi is searching for gold but after he stumbles upon Nazi patrol, a breathtaking and gold-hungry chase through the destroyed and mined Lapland wilderness begins.',
    popularity: 1021.56,
    poster_path: '/ygO9lowFMXWymATCrhoQXd6gCEh.jpg',
    release_date: '2023-01-27',
    title: 'Sisu',
    video: false,
    vote_average: 7.4,
    vote_count: 610,
  },
  {
    adult: false,
    backdrop_path: '/rH3jY9JN9krUyE0Q3WLNtujMs8.jpg',
    genre_ids: [28, 12, 878],
    id: 667538,
    original_language: 'en',
    original_title: 'Transformers: Rise of the Beasts',
    overview:
      "A '90s globetrotting adventure that introduces the Maximals, Predacons, and Terrorcons to the existing battle on earth between Autobots and Decepticons.",
    popularity: 838.469,
    poster_path: '/gPbM0MK8CP8A174rmUwGsADNYKD.jpg',
    release_date: '2023-06-06',
    title: 'Transformers: Rise of the Beasts',
    video: false,
    vote_average: 8.1,
    vote_count: 47,
  },
  {
    adult: false,
    backdrop_path: '/qElNES0sHVQcbzvGrTx7ccpGzij.jpg',
    genre_ids: [878, 28, 18],
    id: 842675,
    original_language: 'zh',
    original_title: '流浪地球2',
    overview: 'A prequel to The Wandering Earth.',
    popularity: 496.708,
    poster_path: '/pR858ihc6Ls9xohpdRJVjV787ml.jpg',
    release_date: '2023-01-22',
    title: 'The Wandering Earth II',
    video: false,
    vote_average: 7.3,
    vote_count: 259,
  },
  {
    adult: false,
    backdrop_path: '/6GIpI3X65J6DT2nSTSga9LnanGJ.jpg',
    genre_ids: [878, 28, 12],
    id: 298618,
    original_language: 'en',
    original_title: 'The Flash',
    overview:
      "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
    popularity: 370.219,
    poster_path: '/67PmbAViFCW3obXxr5Utm9wArIP.jpg',
    release_date: '2023-06-05',
    title: 'The Flash',
    video: false,
    vote_average: 6.2,
    vote_count: 13,
  },
  {
    adult: false,
    backdrop_path: '/wD2kUCX1Bb6oeIb2uz7kbdfLP6k.jpg',
    genre_ids: [27, 53],
    id: 980078,
    original_language: 'en',
    original_title: 'Winnie the Pooh: Blood and Honey',
    overview:
      'Christopher Robin is headed off to college and he has abandoned his old friends, Pooh and Piglet, which then leads to the duo embracing their inner monsters.',
    popularity: 203.884,
    poster_path: '/ewF3IlGscc7FjgGEPcQvZsAsgAW.jpg',
    release_date: '2023-01-27',
    title: 'Winnie the Pooh: Blood and Honey',
    video: false,
    vote_average: 5.7,
    vote_count: 627,
  },
  {
    adult: false,
    backdrop_path: '/bsvplO2lXmtMuxO9TgpD7mlas8K.jpg',
    genre_ids: [27],
    id: 943788,
    original_language: 'en',
    original_title: 'From Black',
    overview:
      "A young mother who's crushed by guilt and shame after the disappearance of her young son five years previously, is offered a bizarre opportunity to learn the truth and set things right. Is she willing to pay the terrifying price for a chance to hold her boy again?",
    popularity: 182.855,
    poster_path: '/9DG2g1Gl1ENAxFONIxxb5FMH99f.jpg',
    release_date: '2023-03-15',
    title: 'From Black',
    video: false,
    vote_average: 5.7,
    vote_count: 13,
  },
  {
    adult: false,
    backdrop_path: '/1PRWW60yQparK1I8Soyy9Evf7Dv.jpg',
    genre_ids: [16, 35, 10751, 18, 12],
    id: 869626,
    original_language: 'en',
    original_title: 'Marcel the Shell with Shoes On',
    overview:
      'Marcel is an adorable one-inch-tall shell who ekes out a colorful existence with his grandmother Connie and their pet lint, Alan. Once part of a sprawling community of shells, they now live alone as the sole survivors of a mysterious tragedy. But when a documentary filmmaker discovers them amongst the clutter of his Airbnb, the short film he posts online brings Marcel millions of passionate fans, as well as unprecedented dangers and a new hope at finding his long-lost family.',
    popularity: 177.672,
    poster_path: '/jaYmP4Ct8YLnxWAW2oYkUjeXtzm.jpg',
    release_date: '2022-06-24',
    title: 'Marcel the Shell with Shoes On',
    video: false,
    vote_average: 7.7,
    vote_count: 283,
  },
  {
    adult: false,
    backdrop_path: '/kgATFkG4SDyengNMmCuwmj7igWW.jpg',
    genre_ids: [14, 28, 12],
    id: 455476,
    original_language: 'en',
    original_title: 'Knights of the Zodiac',
    overview:
      'When a headstrong street orphan, Seiya, in search of his abducted sister unwittingly taps into hidden powers, he discovers he might be the only person alive who can protect a reincarnated goddess, sent to watch over humanity. Can he let his past go and embrace his destiny to become a Knight of the Zodiac?',
    popularity: 171.161,
    poster_path: '/qW4crfED8mpNDadSmMdi7ZDzhXF.jpg',
    release_date: '2023-04-27',
    title: 'Knights of the Zodiac',
    video: false,
    vote_average: 6.3,
    vote_count: 60,
  },
  {
    adult: false,
    backdrop_path: '/x5FuEj9qJX0P4mZkWOgyq6eq7Xm.jpg',
    genre_ids: [18],
    id: 985617,
    original_language: 'en',
    original_title: 'Reality',
    overview:
      'On June 3, 2017, 25-year-old Reality Winner returns from running errands to find two FBI agents at her home in Augusta, Georgia. An Air Force veteran and yoga instructor, Winner spends the next two hours being questioned about her work as an intelligence contractor — specifically, whether she leaked a classified document about Russian interference in the 2016 U.S. elections.',
    popularity: 139.888,
    poster_path: '/4rS1rcaeIJd2zdTn2G8RMfTNeiV.jpg',
    release_date: '2023-06-02',
    title: 'Reality',
    video: false,
    vote_average: 6.6,
    vote_count: 45,
  },
  {
    adult: false,
    backdrop_path: '/a4I481szRmycyreQTLrRe4f4YJe.jpg',
    genre_ids: [80],
    id: 842544,
    original_language: 'en',
    original_title: 'Transfusion',
    overview:
      'Ryan Logan, a former Special Forces operative, is battling to cope with life after the loss of his wife.  He is thrusted into the criminal underworld to keep his only son from being taken from him.',
    popularity: 133.999,
    poster_path: '/bxh5xCCW9Ynfg6EZJWUkc1zqTnr.jpg',
    release_date: '2023-01-05',
    title: 'Transfusion',
    video: false,
    vote_average: 6.3,
    vote_count: 170,
  },
  {
    adult: false,
    backdrop_path: '/7Yuf6j6N76SfqRWqT0I0ZUjICc2.jpg',
    genre_ids: [16, 35, 10751, 14, 10749],
    id: 976573,
    original_language: 'en',
    original_title: 'Elemental',
    overview:
      'In a city where fire, water, land, & air residents live together, a fiery young woman & a go-with-the-flow guy will discover something elemental: How much they have in common.',
    popularity: 124.614,
    poster_path: '/8riWcADI1ekEiBguVB9vkilhiQm.jpg',
    release_date: '2023-06-14',
    title: 'Elemental',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/cUHxmWfkp6se0Rt10Kr86bMCYDE.jpg',
    genre_ids: [35, 18, 36],
    id: 1016084,
    original_language: 'en',
    original_title: 'BlackBerry',
    overview:
      "Two mismatched entrepreneurs – egghead innovator Mike Lazaridis and cut-throat businessman Jim Balsillie – joined forces in an endeavour that was to become a worldwide hit in little more than a decade. The story of the meteoric rise and catastrophic demise of the world's first smartphone.",
    popularity: 120.585,
    poster_path: '/neV35lK7em4rIY9QIoH1cruErPA.jpg',
    release_date: '2023-05-11',
    title: 'BlackBerry',
    video: false,
    vote_average: 7.5,
    vote_count: 39,
  },
  {
    adult: false,
    backdrop_path: '/jOkXeuLo4MBMpeoMa1ClAfTkxuI.jpg',
    genre_ids: [27],
    id: 614479,
    original_language: 'en',
    original_title: 'Insidious: The Red Door',
    overview:
      "To put their demons to rest once and for all, Josh Lambert and a college-aged Dalton Lambert must go deeper into The Further than ever before, facing their family's dark past and a host of new and more horrifying terrors that lurk behind the red door.",
    popularity: 104.79,
    poster_path: '/zXk9Pl3BR8r2o4JvLkFtmBnhuSK.jpg',
    release_date: '2023-07-05',
    title: 'Insidious: The Red Door',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/y5BGYXiqGhOYJ1tuwLGQpO7Idqc.jpg',
    genre_ids: [12, 28],
    id: 335977,
    original_language: 'en',
    original_title: 'Indiana Jones and the Dial of Destiny',
    overview:
      "Finding himself in a new era, approaching retirement, Indy wrestles with fitting into a world that seems to have outgrown him. But as the tentacles of an all-too-familiar evil return in the form of an old rival, Indy must don his hat and pick up his whip once more to make sure an ancient and powerful artifact doesn't fall into the wrong hands.",
    popularity: 97.007,
    poster_path: '/2tgnS3FHueCTXUqiECXyZQuq6gm.jpg',
    release_date: '2023-06-28',
    title: 'Indiana Jones and the Dial of Destiny',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/cKE9qZqYtF4jimf0GFOqKfy7NEU.jpg',
    genre_ids: [35, 10749],
    id: 884605,
    original_language: 'en',
    original_title: 'No Hard Feelings',
    overview:
      'On the brink of losing her childhood home, Maddie discovers an intriguing job listing: wealthy helicopter parents looking for someone to “date” their introverted 19-year-old son, Percy, before he leaves for college. To her surprise, Maddie soon discovers the awkward Percy is no sure thing.',
    popularity: 78.713,
    poster_path: '/5xeNPGbM8ImVdJACUoGpXT8Pxx3.jpg',
    release_date: '2023-06-15',
    title: 'No Hard Feelings',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/bKWFetR4injOJXOGHeLuTD7wHI4.jpg',
    genre_ids: [27, 53, 14],
    id: 994128,
    original_language: 'es',
    original_title: 'Viejos',
    overview:
      'An octogenarian named Manuel falls into a state of dementia after the sudden suicide of his wife, sparking a series of paranormal events that will put his family’s lives at risk.',
    popularity: 78.019,
    poster_path: '/88f35mGJOIE1nXgst5o4FvEDVzr.jpg',
    release_date: '2023-04-21',
    title: 'The Elderly',
    video: false,
    vote_average: 6.6,
    vote_count: 17,
  },
  {
    adult: false,
    backdrop_path: '/5fqbFL4uMmdYPKhQr7PAVFNNgcO.jpg',
    genre_ids: [878, 53],
    id: 942199,
    original_language: 'en',
    original_title: 'Simulant',
    overview:
      'Faye attempts to replace her newly deceased husband, Evan, with an android simulant (SIM). Although SIM Evan appears like human Evan in every way, Faye does not feel the same love for SIM Evan as it does for her. SIM Evan tries to win Faye back while at the same time being on-the-run from a government agent chasing down SIMs who have become “conscious” and could potentially be a threat to humankind.',
    popularity: 72.803,
    poster_path: '/kmDJhZIq1xnu5ZiMOlb0nHJH1qb.jpg',
    release_date: '2023-03-29',
    title: 'Simulant',
    video: false,
    vote_average: 6,
    vote_count: 66,
  },
  {
    adult: false,
    backdrop_path: '/iloUOSs3Rcq3aMr04CrGRWVVBkq.jpg',
    genre_ids: [35, 18, 10749, 878],
    id: 747188,
    original_language: 'en',
    original_title: 'Asteroid City',
    overview:
      'Set in a fictional American desert town circa 1955, the itinerary of a Junior Stargazer/Space Cadet convention (organized to bring together students and parents from across the country for fellowship and scholarly competition) is spectacularly disrupted by world-changing events.',
    popularity: 72.391,
    poster_path: '/qdq40gRS8xKnpFt5V75t6lUHgpx.jpg',
    release_date: '2023-06-09',
    title: 'Asteroid City',
    video: false,
    vote_average: 6.7,
    vote_count: 3,
  },
  {
    adult: false,
    backdrop_path: '/igXrblWrU1uaC09VKyquHHSebr.jpg',
    genre_ids: [28, 53],
    id: 717930,
    original_language: 'en',
    original_title: 'Kandahar',
    overview:
      'After his mission is exposed, an undercover CIA operative stuck deep in hostile territory in Afghanistan must fight his way out, alongside his Afghan translator, to an extraction point in Kandahar, all whilst avoiding elite enemy forces and foreign spies tasked with hunting them down.',
    popularity: 65.5,
    poster_path: '/lCanGgsqF4xD2WA5NF8PWeT3IXd.jpg',
    release_date: '2023-05-25',
    title: 'Kandahar',
    video: false,
    vote_average: 6.3,
    vote_count: 12,
  },
];
